jobs:
    # Perform test builds on relevant distributions.
  - job: Distros
    displayName: Build
    workspace:
      clean: all
    pool:
      name: MLNX
      demands:
      - ucx_docker -equals yes
    strategy:
      matrix:
        ucx_master:
            ucx_tag: master
        ucx_1_12:
            ucx_tag: v1.12.0
        ucx_1_14:
            ucx_tag: v1.14.0
    container: centos7_ib
    steps:
      - checkout: none

      - bash: |
          set -eEx
          git clone --depth 1 -b $(ucx_tag) https://github.com/openucx/ucx.git $(System.DefaultWorkingDirectory)/ucx-$(ucx_tag)
          cd $(System.DefaultWorkingDirectory)/ucx-$(ucx_tag)
          ucx_dir=${PWD}/install
          ./autogen.sh
          ./contrib/configure-release --enable-debug-data --prefix=${ucx_dir}
          make -s -j `nproc`
          make install -s -j `nproc`

          mkdir -p ${ucx_dir}/examples
          cd $(System.DefaultWorkingDirectory)/ucx-$(ucx_tag)/examples
          gcc -lm -lucs -lucp -I${ucx_dir}/include -L${ucx_dir}/lib -o ${ucx_dir}/examples/client_server ucp_client_server.c
          gcc -lm -lucs -lucp -I${ucx_dir}/include -L${ucx_dir}/lib -o ${ucx_dir}/examples/ucp_hworld ucp_hello_world.c
        displayName: Build ucx artifact

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(System.DefaultWorkingDirectory)/ucx-$(ucx_tag)/install'
          artifactName: ucx_$(ucx_tag)_$(Build.BuildId)

  - job: Test_wire_compatibility_cs
    dependsOn: Distros
    displayName: Test wire compatibility (client-server)
    workspace:
      clean: all
    pool:
      name: MLNX
      demands:
      - ucx_docker -equals yes
    strategy:
      matrix:
        ucx1_12_cs:
            ucx_tag: v1.12.0
            client_cmd: client_server -c tag -a
            server_cmd: client_server -c tag
            ucx_env: UCX_TLS=^sm UCX_LOG_LEVEL=info
        ucx1_12_wa:
            ucx_tag: v1.12.0
            client_cmd: ucp_hworld -n
            server_cmd: ucp_hworld
            ucx_env: UCX_TLS=^sm UCX_LOG_LEVEL=info
        ucx1_14_cs:
            ucx_tag: v1.14.0
            client_cmd: client_server -c tag -a
            server_cmd: client_server -c tag
            ucx_env: UCX_TLS=^sm UCX_LOG_LEVEL=info
        ucx1_14_wa:
            ucx_tag: v1.14.0
            client_cmd: ucp_hworld -n
            server_cmd: ucp_hworld
            ucx_env: UCX_TLS=^sm UCX_LOG_LEVEL=info
    container: centos7_ib
    steps:
      - checkout: none
        clean: true
      - task: DownloadBuildArtifacts@0
        displayName: 'Download Build Artifacts'
        inputs:
          artifactName: ucx_master_$(Build.BuildId)
          downloadPath: $(System.DefaultWorkingDirectory)
      - task: DownloadBuildArtifacts@0
        displayName: 'Download Build Artifacts'
        inputs:
          artifactName: ucx_$(ucx_tag)_$(Build.BuildId)
          downloadPath: $(System.DefaultWorkingDirectory)
      - bash: |
          chmod u+rwx $(System.DefaultWorkingDirectory)/ucx_master_$(Build.BuildId) -R
          chmod u+rwx $(System.DefaultWorkingDirectory)/ucx_$(ucx_tag)_$(Build.BuildId) -R
      - bash: |
          set -Eex
          export UCX_LOG_LEVEL=info
          client_server_dir=$(System.DefaultWorkingDirectory)/ucx_$(ucx_tag)_$(Build.BuildId)/examples
          echo $(ucx_env)
          LD_LIBRARY_PATH=${UCX_LEGACY_LIB_PATH} ${client_server_dir}/$(server_cmd) &
          server_pid=$!
          sleep 5
          LD_LIBRARY_PATH=${UCX_PR_LIB_PATH} ${client_server_dir}/$(client_cmd) 127.0.0.1
          kill -9 $server_pid
        env:
          UCX_PR_LIB_PATH: $(System.DefaultWorkingDirectory)/ucx_master_$(Build.BuildId)/lib
          UCX_LEGACY_LIB_PATH: $(System.DefaultWorkingDirectory)/ucx_$(ucx_tag)_$(Build.BuildId)/lib
        displayName: Test server is legacy client is master
        timeoutInMinutes: 5
      - bash: |
          set -Eex
          export UCX_LOG_LEVEL=info
          client_server_dir=$(System.DefaultWorkingDirectory)/ucx_$(ucx_tag)_$(Build.BuildId)/examples
          echo $(ucx_env)
          LD_LIBRARY_PATH=${UCX_PR_LIB_PATH} ${client_server_dir}/$(server_cmd) &
          server_pid=$!
          sleep 5
          LD_LIBRARY_PATH=${UCX_LEGACY_LIB_PATH} ${client_server_dir}/$(client_cmd) 127.0.0.1
          kill -9 $server_pid
        env:
          UCX_PR_LIB_PATH: $(System.DefaultWorkingDirectory)/ucx_master_$(Build.BuildId)/lib
          UCX_LEGACY_LIB_PATH: $(System.DefaultWorkingDirectory)/ucx_$(ucx_tag)_$(Build.BuildId)/lib
        displayName: Test server is master client is legacy
        timeoutInMinutes: 5
