variables:
  DOCKER_OPT_VOLUMES: -v /hpc/local:/hpc/local -v /auto/sw_tools:/auto/sw_tools
  DOCKER_OPT_IB: --ulimit memlock=-1:-1 --device=/dev/infiniband/ --net=host
  DOCKER_OPT_GPU: --gpus all --device=/dev/gdrdrv $(DOCKER_OPT_IB)
  DOCKER_OPT_ARGS: --cap-add=SYS_PTRACE

resources:
  containers:
    - container: centos7
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/centos7:4
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: centos7_ib
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/centos7:5
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES) $(DOCKER_OPT_IB)
    - container: centos7_cuda11
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/centos7-mofed5.4-cuda11:1
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES) $(DOCKER_OPT_GPU)
    - container: centos8_cuda11
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/centos8-mofed5-cuda11:2
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES) $(DOCKER_OPT_GPU)
    - container: fedora
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/fedora33:1
      options: $(DOCKER_OPT_ARGS)
    - container: fedora34
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/fedora34:2
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: coverity_rh7
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/coverity:mofed-5.1-2.3.8.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: rhel76
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/rhel7.6/builder:mofed-5.0-1.0.0.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: rhel76_mofed47
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/rhel7.6/builder:mofed-4.7-1.0.0.1
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: rhel74
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/rhel7.4/builder:mofed-5.0-1.0.0.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: rhel72
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/rhel7.2/builder:mofed-5.0-1.0.0.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: rhel82
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/rhel8.2/builder:mofed-5.0-1.0.0.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: rhel90
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/rhel9.0/builder:mofed-5.6-0.5.0.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: ubuntu2004
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/ubuntu20.04/builder:mofed-5.0-1.0.0.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: ubuntu2204
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/ubuntu22.04/builder:mofed-5.7-0.2.3.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: ubuntu2204_ib
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/ubuntu22.04/builder:mofed-5.7-0.2.3.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES) $(DOCKER_OPT_IB)
    - container: ubuntu2210
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/ubuntu22.10/builder:mofed-5.8-0.2.1.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: ubuntu1804
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/ubuntu18.04/builder:mofed-5.0-1.0.0.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: debian113
      image: rdmz-harbor.rdmz.labs.mlnx/hpcx/x86_64/debian11.3/builder:mofed-5.8-3.0.7.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: debian109
      image: rdmz-harbor.rdmz.labs.mlnx/hpcx/x86_64/debian10.9/builder:mofed-5.8-3.0.7.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: sles15sp2
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/sles15sp2/builder:mofed-5.0-1.0.0.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: sles12sp5
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/sles12sp5/builder:mofed-5.0-1.0.0.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: centos7_cuda_11_0
      image: nvidia/cuda:11.0.3-devel-centos7
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: centos7_cuda_11_1
      image: nvidia/cuda:11.1.1-devel-centos7
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: centos7_cuda_11_2
      image: nvidia/cuda:11.2.2-devel-centos7
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: centos7_cuda_11_3
      image: nvidia/cuda:11.3.1-devel-centos7
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: centos7_cuda_11_4
      image: nvidia/cuda:11.4.3-devel-centos7
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubi8_cuda_11_5
      image: nvidia/cuda:11.5.2-devel-ubi8
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubi8_cuda_11_6
      image: nvidia/cuda:11.6.2-devel-ubi8
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu18_cuda_11_0
      image: nvidia/cuda:11.0.3-devel-ubuntu18.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu18_cuda_11_1
      image: nvidia/cuda:11.1.1-devel-ubuntu18.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu18_cuda_11_2
      image: nvidia/cuda:11.2.2-devel-ubuntu18.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu18_cuda_11_3
      image: nvidia/cuda:11.3.1-devel-ubuntu18.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu18_cuda_11_4
      image: nvidia/cuda:11.4.3-devel-ubuntu18.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu18_cuda_11_5
      image: nvidia/cuda:11.5.2-devel-ubuntu18.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu18_cuda_11_6
      image: nvidia/cuda:11.6.2-devel-ubuntu18.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu20_cuda_11_0
      image: nvidia/cuda:11.0.3-devel-ubuntu20.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu20_cuda_11_1
      image: nvidia/cuda:11.1.1-devel-ubuntu20.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu20_cuda_11_2
      image: nvidia/cuda:11.2.2-devel-ubuntu20.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu20_cuda_11_3
      image: nvidia/cuda:11.3.1-devel-ubuntu20.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu20_cuda_11_4
      image: nvidia/cuda:11.4.3-devel-ubuntu20.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu20_cuda_11_5
      image: nvidia/cuda:11.5.2-devel-ubuntu20.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu20_cuda_11_6
      image: nvidia/cuda:11.6.2-devel-ubuntu20.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: centos7_cuda_12_0
      image: nvidia/cuda:12.0.0-devel-centos7
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: centos7_cuda_12_1
      image: nvidia/cuda:12.1.0-devel-centos7
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu18_cuda_12_0
      image: nvidia/cuda:12.0.0-devel-ubuntu18.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu18_cuda_12_1
      image: nvidia/cuda:12.1.0-devel-ubuntu18.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu20_cuda_12_0
      image: nvidia/cuda:12.0.0-devel-ubuntu20.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu20_cuda_12_1
      image: nvidia/cuda:12.1.0-devel-ubuntu20.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu22_cuda_12_0
      image: nvidia/cuda:12.0.0-devel-ubuntu22.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: ubuntu22_cuda_12_1
      image: nvidia/cuda:12.1.0-devel-ubuntu22.04
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_GPU)
    - container: centos8_cuda11
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/centos8-mofed5-cuda11:1
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES) $(DOCKER_OPT_GPU)
    - container: centos8_cuda11_asan
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/centos8-mofed23-cuda11_asan:1
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES) $(DOCKER_OPT_GPU)
    - container: ubuntu16_cuda11
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/ubuntu16.04-mofed5-cuda11:1
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES) $(DOCKER_OPT_GPU)
    - container: ubuntu18_cuda11
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/ubuntu18.04-mofed5-cuda11:1
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES) $(DOCKER_OPT_GPU)
    - container: ubuntu20_cuda11
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/ubuntu20.04-mofed5-cuda11:1
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES) $(DOCKER_OPT_GPU)
    - container: ubuntu2004_rocm_5_4_0
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/ubuntu2004:rocm_5_4_0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)
    - container: ubuntu22_cuda12
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/ubuntu22.04-mofed5-cuda12:3
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES) $(DOCKER_OPT_GPU)
    - container: ubuntu2204_rocm_6_0_0
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/x86_64/ubuntu2204:rocm-6.0.0
      options: $(DOCKER_OPT_ARGS) $(DOCKER_OPT_VOLUMES)

stages:
  - stage: Tests
    jobs:
    - template: tests.yml
      parameters:
        name: gpu
        demands: ucx_gpu_dmabuf -equals yes
        test_perf: 1
        container: centos7_cuda11


#  - stage: Cuda_compatible
#    dependsOn: [Static_check]
#    jobs:
#    - template: cuda/cuda_compatible.yml
